security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database:
            entity:
                class: App\Entity\User
                property: email

    encoders:
        App\Entity\User:
            algorithm:            bcrypt
            cost:                 13
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER: ~
        ROLE_CASHIER: ROLE_USER
        ROLE_MERCHANT: ROLE_CASHIER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: in_memory

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: login_merchant
                check_path: login_merchant
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
