security:
    providers:
        database:
            id: App\Repository\UserRepository

    encoders:
        App\Entity\User:
            algorithm:            bcrypt
            cost:                 10

    role_hierarchy:
        ROLE_USER: ~
        ROLE_CASHIER: ROLE_USER
        ROLE_MERCHANT: ROLE_CASHIER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 1200000 # 2 week in seconds
                path:     '/'
                always_remember_me: true
            logout:
                path:   login_out
                invalidate_session: false

            guard:
                provider: database
                authenticators: ['App\Security\FormAuthenticator']
                entry_point:  'App\Security\FormAuthenticator'
