version: "2.1"

services:
  lnd:
    image: lightningsale/docker-lnd:master
    env_file:
      - .env
    environment:
      - "RPCLISTEN=localhost:10009"
      - "RESTLISTEN=0.0.0.0:8080"
      - "EXTERNALIP=92.221.98.237:9736"
    volumes:
      - lnd:/root/.lnd
    ports:
      - 9736:9736
      - 127.0.0.1:8080:8080
    expose: ["8080"]
    entrypoint: ["./start-lnd.sh"]
    hostname: lnd
    command:
      - "--bitcoin.node=neutrino"
      - "--neutrino.connect=faucet.lightning.community"
      - "--autopilot.active"
      - "--listen=0.0.0.0:9736"
      - "--alias=Lightning.Sale"
      - "--color=#312546"
  pos:
    build:
      dockerfile: Dockerfile.xdebug
      context: .
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - mysql
      - lnd
    volumes:
      - .:/var/www
      - lnd:/var/www/var/lnd
  mysql:
    image: mysql
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
  redis:
    image: redis
volumes:
  lnd: ~
  mysql: ~
