version: "2.1"

services:
  lnd:
    image: lightningsale/docker-lnd
    env_file:
      - .env
    volumes:
      - lnd:/root/.lnd
    ports:
      - 9736:9736
      - 127.0.0.1:10009:10009
    expose: ["8080"]
    entrypoint: ["./start-lnd.sh"]
    hostname: lnd
    command:
      - "--neutrino.active"
      - "--neutrino.connect=faucet.lightning.community"
      - "--autopilot.active"
      - "--no-macaroons"
      - "--peerport=9736"
  pos:
    build:
      dockerfile: Dockerfile.xdebug
      context: .
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - mysql
      - lnd
    volumes:
      - .:/var/www
      - lnd:/var/www/var/lnd
  mysql:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
  redis:
    image: redis
volumes:
  lnd: ~
  mysql: ~
