version: "2.1"

services:
  lnd:
    image: lightningsale/docker-lnd
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER=lightningsale
      - RPCPASS=lightningsale
      - NETWORK=testnet
      - CHAIN=bitcoin
      - DEBUG=info
      - EXTERNALIP=127.0.0.1
    volumes:
      - /root/.lnd:/root/.lnd
    ports:
      - 9735:9735
    expose: ["10009", "8080"]
    entrypoint: ["./start-lnd.sh"]
    command:
      - "--neutrino.active"
      - "--neutrino.connect=faucet.lightning.community"
      - "--autopilot.active"
  pos:
    build:
      dockerfile: Dockerfile.xdebug
      context: .
    ports:
      - 80:80
    environment:
      - DATABASE_URL=mysql://root:abcd1234@mysql:3306/lightningsale
    depends_on:
      - mysql
      - lnd
    volumes:
      - .:/var/www

  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234