# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    lnd_cert: "%kernel.project_dir%/var/lnd/tls.cert"
    external_ip: "%env(EXTERNALIP)%"
    external_port: "%env(EXTERNALPORT)%"
    redis_dsn: "redis://%env(REDIS_URL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    LightningSale\LndRest\Resource\LndClient:
        class: LightningSale\LndRest\Resource\LndClient
        factory: ['@App\Service\LightningServiceFactory','getLndClient']
    App\Service\LightningServiceFactory:
        arguments: ["%lnd_cert%", "%env(RPCPASS)%", "%env(RPCUSER)%", "%env(LND_HOST)%", "%env(LND_PORT)%"]

    App\Service\ExchangeService:
        arguments: [!tagged app.exchange]


    Predis\Client:
        factory: 'Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection'
        arguments: ["%redis_dsn%"]

    Symfony\Component\Cache\Adapter\RedisAdapter:
        arguments: ['@Predis\Client']

    Symfony\Component\Cache\Adapter\AbstractAdapter:
        alias: Symfony\Component\Cache\Adapter\RedisAdapter