# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    lnd_cert: "%kernel.project_dir%/var/lnd/tls.cert"
    external_ip: "%env(EXTERNALIP)%"
    external_port: "%env(EXTERNALPORT)%"
    redis_dsn: "redis://%env(REDIS_URL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    LightningSale\LndClient\Client: '@LightningSale\LndClient\RestClient'
    LightningSale\LndClient\RestClient:
        class: LightningSale\LndClient\RestClient
        factory: ['LightningSale\LndClient\ClientFactory','createRestClient']
        arguments: ["%env(LND_HOST)%", "%env(LND_PORT)%", "%env(RPCUSER)%", "%env(RPCPASS)%", "%lnd_cert%", "@logger"]

    App\Service\ExchangeService:
        arguments: [!tagged app.exchange]


    Predis\Client:
        factory: 'Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection'
        arguments: ["%redis_dsn%"]

    Symfony\Component\Cache\Simple\RedisCache:
        arguments: ['@Predis\Client']

    Symfony\Component\Cache\Simple\AbstractCache:
        alias: Symfony\Component\Cache\Simple\RedisCache